### ISSUE TITLE
Radarr Transparent Profile Incorrect

### ISSUE THREAD

**Issue by lostbow** [santiagosayshey/Profilarr#4]
Unless I am missing something it appears the Transparent Profile for Radarr is setup incorrectly. 

When looking at the file under profiles/1080p Transparent (Radarr).json it shows many FormatItems and an associated score, when importing that into Radarr only Hulu and IMAX get an actual score, then there are a bunch of 0 score items and 3D and LQ get -9999. Looking at the FormatItems the Names it is targeting don't exist after running the Radarr custom_formats import. 

I am going to try and fix it on my own but wanted this document to make sure I am not missing anything and for other people who may run into this.

**Comment by lostbow** [comment]
I figured it out, I've been looking for a bit and figures I figure it out right as I make this request. I ran the exportarr before the importarr and had trashguides custom formats setup. Apparently that will overwrite the original custom_format (Radarr).json.

**Comment by santiagosayshey** [comment]
> I figured it out, I've been looking for a bit and figures I figure it out right as I make this request. I ran the exportarr before the importarr and had trashguides custom formats setup. Apparently that will overwrite the original custom_format (Radarr).json.

Thanks for adding your experience here. This wasn't a scenario I had really considered when writing the code. Usually because I'm needing to always update the custom format file with new updates, it was easier to overwrite the exisiting one.

For now, I'll add a warning to the README about this and look into seperating the folders Profilarr imports from / exports too.
